<?php

return [
    'roles' => [
        'Super Admin',
        'Hospital Admin',
        'Receptionist',
        'Doctor',
        'Nurse',
        'Lab Scientist',
        'Pharmacist',
        'Accountant',
        'Patient',
    ],

    'modules' => [
        'Core' => 'System foundation, dashboard, and shared services.',
        'Auth' => 'Authentication, profile management, and access control.',
        'CMS' => 'Public website pages, departments, doctors, and blog content.',
        'Patients' => 'Registration, patient records, vitals, and visit history.',
        'Doctors' => 'Doctor profiles, consultations, and patient assignments.',
        'Appointments' => 'Booking, queue management, and schedule handling.',
        'Pharmacy' => 'Medicine inventory, dispensing, and stock tracking.',
        'Laboratory' => 'Lab requests, result uploads, and PDF reports.',
        'Billing' => 'Invoices, payments, and revenue tracking.',
        'Reports' => 'Daily summaries, analytics, and operational insights.',
        'Notifications' => 'System alerts, reminders, and outbound messaging.',
        'Settings' => 'Hospital profile, SEO, and platform configuration.',
    ],

    'permissions' => [
        'dashboard.view',
        'cms.view',
        'cms.manage',
        'patients.view',
        'patients.create',
        'patients.update',
        'patients.delete',
        'doctors.view',
        'doctors.create',
        'doctors.update',
        'appointments.view',
        'appointments.create',
        'appointments.update',
        'appointments.cancel',
        'laboratory.view',
        'laboratory.manage',
        'pharmacy.view',
        'pharmacy.manage',
        'billing.view',
        'billing.manage',
        'reports.view',
        'notifications.view',
        'notifications.manage',
        'settings.view',
        'settings.manage',
        'users.view',
        'users.manage',
        'roles.view',
        'roles.manage',
        'activity-log.view',
    ],
];
